name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (optional)
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: List project files (debugging)
      run: ls -lah

    - name: Build project
      run: make

    - name: Run tests
      run: make check

    - name: Run distribution check (optional)
      run: make distcheck
